version: '3.9'
networks:
  default:
    name: kotlin-coroutine-benchmark-network
    driver: bridge
services:
  benchmark-target:
    container_name: ${BENCHMARK_TARGET}
    image: ${BENCHMARK_TARGET}:latest
    ports:
      - '8080:8080'
    env_file:
      - ${BENCHMARK_TARGET_ENV_FILE}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
  gatling-runner:
    container_name: gatling-runner
    build: gatling/
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    links:
      - benchmark-target:${BENCHMARK_TARGET}
    volumes:
      - ./docker-cache/gatling-runner/.gradle:/usr/src/app/.gradle
      - ./docker-cache/gatling-runner/build:/usr/src/app/build
    env_file:
      - ${GATLING_RUNNER_ENV_FILE}
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 6G
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - benchmark-target:${BENCHMARK_TARGET}
    ports:
      - '9090:9090'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  grafana:
    container_name: grafana
    volumes:
      - ./docker-cache/grafana:/var/lib/grafana
    image: grafana/grafana
    links:
      - prometheus
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
