version: '3.9'
services:
  s3-upload:
    image: minio/mc
    volumes:
       - ./upload:/upload
       - ./cf-upload.sh:/cf-upload.sh
    env_file: cf.secret.env
    entrypoint: "bash -c 'bash cf-upload.sh'"
